//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQTTestInterface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQTTestInterface.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com,org,gov,mil.
        /// </summary>
        internal static string acceptableTopLevelDomains {
            get {
                return ResourceManager.GetString("acceptableTopLevelDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Validator.
        /// </summary>
        internal static string accountValidatorMessageWindowTitle {
            get {
                return ResourceManager.GetString("accountValidatorMessageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Canceled!.
        /// </summary>
        internal static string actionCanceledMessageWindowTitle {
            get {
                return ResourceManager.GetString("actionCanceledMessageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Connection Configuration Errors.
        /// </summary>
        internal static string ADConnectionErrorsMessageWindowTitle {
            get {
                return ResourceManager.GetString("ADConnectionErrorsMessageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ADIP],[ESXIP],[HULL],[LOCPH],[REDHAT],[USER][DA],[USER][ESX],[USER][LOC],[USER][REG],[USER][SA],[USER][SM],[USER][SSH],[USER][WA],[WEBTEST][EXTERNAL],[WEBTEST][INTERNAL].
        /// </summary>
        internal static string configSettingsLineList {
            get {
                return ResourceManager.GetString("configSettingsLineList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\\SSAManager.conf.
        /// </summary>
        internal static string configurationFilePath {
            get {
                return ResourceManager.GetString("configurationFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Manager.
        /// </summary>
        internal static string configurationManagerMessageWindowTitle {
            get {
                return ResourceManager.GetString("configurationManagerMessageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Default Test Password Setter.
        /// </summary>
        internal static string defaultPassMessageWindowTitle {
            get {
                return ResourceManager.GetString("defaultPassMessageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HULL]&lt;HULL#&gt;
        ///[ESXIP]&lt;IP&gt;;&lt;IP&gt;;&lt;IP&gt;;&lt;IP&gt;;&lt;IP&gt;;&lt;IP&gt;;
        ///[ADIP]&lt;IP&gt;;&lt;IP&gt;;
        ///[USER][REG]&lt;DOMAIN&gt;\&lt;USERNAME&gt;
        ///[USER][DA]&lt;DOMAIN&gt;\&lt;USERNAME&gt;
        ///[USER][SA]&lt;DOMAIN&gt;\&lt;USERNAME&gt;
        ///[USER][WA]&lt;DOMAIN&gt;\&lt;USERNAME&gt;
        ///[USER][SSH]&lt;USERNAME&gt;
        ///[USER][SM]&lt;USERNAME&gt;
        ///[USER][ESX]&lt;USERNAME&gt;
        ///[USER][LOC]admin
        ///[WEBTEST][EXTERNAL]http://web.site.one.com/;http://web.site.two.com/;http://web.site.three.com/;http://web.site.four.com/
        ///[WEBTEST][INTERNAL]http://web.site.one.com/;http://web.site.two.com/;http://web.site.three.com/;http://web [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultSettings {
            get {
                return ResourceManager.GetString("defaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;IP&gt;;&lt;IP&gt;;.
        /// </summary>
        internal static string dftADIP {
            get {
                return ResourceManager.GetString("dftADIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DOMAIN&gt;\&lt;USERNAME&gt;.
        /// </summary>
        internal static string dftDA {
            get {
                return ResourceManager.GetString("dftDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;USERNAME&gt;.
        /// </summary>
        internal static string dftESX {
            get {
                return ResourceManager.GetString("dftESX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;IP&gt;;&lt;IP&gt;;&lt;IP&gt;;&lt;IP&gt;;&lt;IP&gt;;&lt;IP&gt;;.
        /// </summary>
        internal static string dftESXIP {
            get {
                return ResourceManager.GetString("dftESXIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;HULL#&gt;.
        /// </summary>
        internal static string dftHull {
            get {
                return ResourceManager.GetString("dftHull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5.
        /// </summary>
        internal static string dftPH {
            get {
                return ResourceManager.GetString("dftPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DOMAIN&gt;\&lt;USERNAME&gt;.
        /// </summary>
        internal static string dftReg {
            get {
                return ResourceManager.GetString("dftReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedHatLinuxVM1;RedHatLinuxVM2;RedHatLinuxVM3;.
        /// </summary>
        internal static string dftRH {
            get {
                return ResourceManager.GetString("dftRH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DOMAIN&gt;\&lt;USERNAME&gt;.
        /// </summary>
        internal static string dftSA {
            get {
                return ResourceManager.GetString("dftSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;USERNAME&gt;.
        /// </summary>
        internal static string dftSM {
            get {
                return ResourceManager.GetString("dftSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;USERNAME&gt;.
        /// </summary>
        internal static string dftSSH {
            get {
                return ResourceManager.GetString("dftSSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string dftUser {
            get {
                return ResourceManager.GetString("dftUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DOMAIN&gt;\&lt;USERNAME&gt;.
        /// </summary>
        internal static string dftWA {
            get {
                return ResourceManager.GetString("dftWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://web.site.one.com/;http://web.site.two.com/;http://web.site.three.com/;http://web.site.four.com/.
        /// </summary>
        internal static string dftWebExt {
            get {
                return ResourceManager.GetString("dftWebExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://web.site.one.com/;http://web.site.two.com/;http://web.site.three.com/;http://web.site.four.com/.
        /// </summary>
        internal static string dftWebInt {
            get {
                return ResourceManager.GetString("dftWebInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\\ExternalSiteTestLog.txt.
        /// </summary>
        internal static string externalSiteTestLogFilePath {
            get {
                return ResourceManager.GetString("externalSiteTestLogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Site Test Manager.
        /// </summary>
        internal static string externalSiteTestManagerMessageWindowTitle {
            get {
                return ResourceManager.GetString("externalSiteTestManagerMessageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hull and User Validator.
        /// </summary>
        internal static string hullandUserValidatorMessageWindowTitle {
            get {
                return ResourceManager.GetString("hullandUserValidatorMessageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address Validator.
        /// </summary>
        internal static string ipAddressValidatorMessageWindowTitle {
            get {
                return ResourceManager.GetString("ipAddressValidatorMessageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Validator.
        /// </summary>
        internal static string loginValidatorMessageWindowTitle {
            get {
                return ResourceManager.GetString("loginValidatorMessageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Ping Test,Check RBAC,Check Java Versioning,Check All Services,Get Registry Data.
        /// </summary>
        internal static string menuConfigManagementItems {
            get {
                return ResourceManager.GetString("menuConfigManagementItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows &amp; Local Settings,Server Address Settings,Ship and User Settings,Website List Settings,Deck Profile Settings.
        /// </summary>
        internal static string menuSettingsItems {
            get {
                return ResourceManager.GetString("menuSettingsItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Website Tests,External Website Tests.
        /// </summary>
        internal static string menuSQTTestItems {
            get {
                return ResourceManager.GetString("menuSQTTestItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power On Machines,Power Off Machines,Check VM Tools,Snapshot All Virtual Machines,Export Deck.
        /// </summary>
        internal static string menuVMFunctionsItems {
            get {
                return ResourceManager.GetString("menuVMFunctionsItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[A-Za-z0-9_\./:-]+$.
        /// </summary>
        internal static string mixedRegex {
            get {
                return ResourceManager.GetString("mixedRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Active Directory Connection Settings!.
        /// </summary>
        internal static string noADConfigString {
            get {
                return ResourceManager.GetString("noADConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Error! Reload program or re-enter correct values!.
        /// </summary>
        internal static string noConfigString {
            get {
                return ResourceManager.GetString("noConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[\d]+$.
        /// </summary>
        internal static string numberRegex {
            get {
                return ResourceManager.GetString("numberRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Validator.
        /// </summary>
        internal static string passwordValidatorWindowTitle {
            get {
                return ResourceManager.GetString("passwordValidatorWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQ01,WEB,IAEXET,EX01,EX02,FS01,DC01,DC02,YUM,VCSA.
        /// </summary>
        internal static string powerOffPrimaries {
            get {
                return ResourceManager.GetString("powerOffPrimaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC01,VCSA,YUM,DC02,SQ01,FS01,ISE01,ISE02,EX01,EX02,WEB,IAEXET,EM01,EM02,IM01,IM02.
        /// </summary>
        internal static string powerOnPrimaries {
            get {
                return ResourceManager.GetString("powerOnPrimaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSA Deck Manager 1.0,Virtual Machine Functions,Configuration Management,Tests,Deck Settings.
        /// </summary>
        internal static string topMenuList {
            get {
                return ResourceManager.GetString("topMenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Manager.
        /// </summary>
        internal static string websiteManagerMessageWindowTitle {
            get {
                return ResourceManager.GetString("websiteManagerMessageWindowTitle", resourceCulture);
            }
        }
    }
}
